/**
SVG-значки и операции их создания имеют общий результат: SVG data URL.
Именованные участники сохраняют собственное содержимое и параметры создания.

@packageDocumentation
*/
export {default as applyIcon} from "@zavx0z/immersive-ui-theme-icon-apply"
export {default as arrowDownIcon} from "@zavx0z/immersive-ui-theme-icon-arrow-down"
export {default as arrowUpIcon} from "@zavx0z/immersive-ui-theme-icon-arrow-up"
export {default as breakpointIcon} from "@zavx0z/immersive-ui-theme-icon-breakpoint"
export {default as chevronDownIcon} from "@zavx0z/immersive-ui-theme-icon-chevron-down"
export {default as chevronRightIcon} from "@zavx0z/immersive-ui-theme-icon-chevron-right"
export {default as clearIcon} from "@zavx0z/immersive-ui-theme-icon-clear"
export {default as closeIcon} from "@zavx0z/immersive-ui-theme-icon-close"
export {default as collapseAllIcon} from "@zavx0z/immersive-ui-theme-icon-collapse-all"
export {default as databaseIcon} from "@zavx0z/immersive-ui-theme-icon-database"
export {default as executionPointIcon} from "@zavx0z/immersive-ui-theme-icon-execution-point"
export {default as expandAllIcon} from "@zavx0z/immersive-ui-theme-icon-expand-all"
export {default as expandIcon} from "@zavx0z/immersive-ui-theme-icon-expand"
export {default as folderIcon} from "@zavx0z/immersive-ui-theme-icon-folder"
export {default as homeIcon} from "@zavx0z/immersive-ui-theme-icon-home"
export {default as iconSvg} from "@zavx0z/immersive-ui-theme-icon-compose"
export {default as imageIcon} from "@zavx0z/immersive-ui-theme-icon-image"
export {default as languageIcon} from "@zavx0z/immersive-ui-theme-icon-language"
export {default as minusIcon} from "@zavx0z/immersive-ui-theme-icon-minus"
export {default as pickerIcon} from "@zavx0z/immersive-ui-theme-icon-picker"
export {default as pinIcon} from "@zavx0z/immersive-ui-theme-icon-pin"
export {default as plusIcon} from "@zavx0z/immersive-ui-theme-icon-plus"
export {default as resourceIcon} from "@zavx0z/immersive-ui-theme-icon-resource"
export {default as runIcon} from "@zavx0z/immersive-ui-theme-icon-run"
export {default as searchIcon} from "@zavx0z/immersive-ui-theme-icon-search"
export {default as selectOpenedItemIcon} from "@zavx0z/immersive-ui-theme-icon-select-opened-item"
export {default as settingsIcon} from "@zavx0z/immersive-ui-theme-icon-setting"
export {default as visibilityOnIcon} from "@zavx0z/immersive-ui-theme-icon-visibility-on"
export type {ImmersiveUiThemeIcon} from "./contract"
export type {ImmersiveUiThemeIconApply} from "@zavx0z/immersive-ui-theme-icon-apply"
export type {ImmersiveUiThemeIconArrowDown} from "@zavx0z/immersive-ui-theme-icon-arrow-down"
export type {ImmersiveUiThemeIconArrowUp} from "@zavx0z/immersive-ui-theme-icon-arrow-up"
export type {ImmersiveUiThemeIconBreakpoint} from "@zavx0z/immersive-ui-theme-icon-breakpoint"
export type {ImmersiveUiThemeIconChevronDown} from "@zavx0z/immersive-ui-theme-icon-chevron-down"
export type {ImmersiveUiThemeIconChevronRight} from "@zavx0z/immersive-ui-theme-icon-chevron-right"
export type {ImmersiveUiThemeIconClear} from "@zavx0z/immersive-ui-theme-icon-clear"
export type {ImmersiveUiThemeIconClose} from "@zavx0z/immersive-ui-theme-icon-close"
export type {ImmersiveUiThemeIconCollapseAll} from "@zavx0z/immersive-ui-theme-icon-collapse-all"
export type {ImmersiveUiThemeIconCompose} from "@zavx0z/immersive-ui-theme-icon-compose"
export type {ImmersiveUiThemeIconDatabase} from "@zavx0z/immersive-ui-theme-icon-database"
export type {ImmersiveUiThemeIconExecutionPoint} from "@zavx0z/immersive-ui-theme-icon-execution-point"
export type {ImmersiveUiThemeIconExpand} from "@zavx0z/immersive-ui-theme-icon-expand"
export type {ImmersiveUiThemeIconExpandAll} from "@zavx0z/immersive-ui-theme-icon-expand-all"
export type {ImmersiveUiThemeIconFolder} from "@zavx0z/immersive-ui-theme-icon-folder"
export type {ImmersiveUiThemeIconHome} from "@zavx0z/immersive-ui-theme-icon-home"
export type {ImmersiveUiThemeIconImage} from "@zavx0z/immersive-ui-theme-icon-image"
export type {ImmersiveUiThemeIconLanguage} from "@zavx0z/immersive-ui-theme-icon-language"
export type {ImmersiveUiThemeIconMinus} from "@zavx0z/immersive-ui-theme-icon-minus"
export type {ImmersiveUiThemeIconPicker} from "@zavx0z/immersive-ui-theme-icon-picker"
export type {ImmersiveUiThemeIconPin} from "@zavx0z/immersive-ui-theme-icon-pin"
export type {ImmersiveUiThemeIconPlus} from "@zavx0z/immersive-ui-theme-icon-plus"
export type {ImmersiveUiThemeIconResource} from "@zavx0z/immersive-ui-theme-icon-resource"
export type {ImmersiveUiThemeIconRun} from "@zavx0z/immersive-ui-theme-icon-run"
export type {ImmersiveUiThemeIconSearch} from "@zavx0z/immersive-ui-theme-icon-search"
export type {ImmersiveUiThemeIconSelectOpenedItem} from "@zavx0z/immersive-ui-theme-icon-select-opened-item"
export type {ImmersiveUiThemeIconSetting} from "@zavx0z/immersive-ui-theme-icon-setting"
export type {ImmersiveUiThemeIconVisibilityOn} from "@zavx0z/immersive-ui-theme-icon-visibility-on"
