/**
SVG-значки и операции их создания имеют общий результат: SVG data URL.
Именованные участники сохраняют собственное содержимое и параметры создания.

@packageDocumentation
*/
export {default as applyIcon} from "@immersive-ui-theme-icon/apply"
export {default as arrowDownIcon} from "@immersive-ui-theme-icon/arrow-down"
export {default as arrowUpIcon} from "@immersive-ui-theme-icon/arrow-up"
export {default as breakpointIcon} from "@immersive-ui-theme-icon/breakpoint"
export {default as chevronDownIcon} from "@immersive-ui-theme-icon/chevron-down"
export {default as chevronRightIcon} from "@immersive-ui-theme-icon/chevron-right"
export {default as clearIcon} from "@immersive-ui-theme-icon/clear"
export {default as closeIcon} from "@immersive-ui-theme-icon/close"
export {default as collapseAllIcon} from "@immersive-ui-theme-icon/collapse-all"
export {default as databaseIcon} from "@immersive-ui-theme-icon/database"
export {default as executionPointIcon} from "@immersive-ui-theme-icon/execution-point"
export {default as expandAllIcon} from "@immersive-ui-theme-icon/expand-all"
export {default as expandIcon} from "@immersive-ui-theme-icon/expand"
export {default as folderIcon} from "@immersive-ui-theme-icon/folder"
export {default as homeIcon} from "@immersive-ui-theme-icon/home"
export {default as iconSvg} from "@immersive-ui-theme-icon/compose"
export {default as imageIcon} from "@immersive-ui-theme-icon/image"
export {default as languageIcon} from "@immersive-ui-theme-icon/language"
export {default as minusIcon} from "@immersive-ui-theme-icon/minus"
export {default as pickerIcon} from "@immersive-ui-theme-icon/picker"
export {default as pinIcon} from "@immersive-ui-theme-icon/pin"
export {default as plusIcon} from "@immersive-ui-theme-icon/plus"
export {default as resourceIcon} from "@immersive-ui-theme-icon/resource"
export {default as runIcon} from "@immersive-ui-theme-icon/run"
export {default as searchIcon} from "@immersive-ui-theme-icon/search"
export {default as selectOpenedItemIcon} from "@immersive-ui-theme-icon/select-opened-item"
export {default as settingsIcon} from "@immersive-ui-theme-icon/setting"
export {default as visibilityOnIcon} from "@immersive-ui-theme-icon/visibility-on"
export type {ImmersiveUiThemeIcon} from "./contract"
export type {ImmersiveUiThemeIconApply} from "@immersive-ui-theme-icon/apply"
export type {ImmersiveUiThemeIconArrowDown} from "@immersive-ui-theme-icon/arrow-down"
export type {ImmersiveUiThemeIconArrowUp} from "@immersive-ui-theme-icon/arrow-up"
export type {ImmersiveUiThemeIconBreakpoint} from "@immersive-ui-theme-icon/breakpoint"
export type {ImmersiveUiThemeIconChevronDown} from "@immersive-ui-theme-icon/chevron-down"
export type {ImmersiveUiThemeIconChevronRight} from "@immersive-ui-theme-icon/chevron-right"
export type {ImmersiveUiThemeIconClear} from "@immersive-ui-theme-icon/clear"
export type {ImmersiveUiThemeIconClose} from "@immersive-ui-theme-icon/close"
export type {ImmersiveUiThemeIconCollapseAll} from "@immersive-ui-theme-icon/collapse-all"
export type {ImmersiveUiThemeIconCompose} from "@immersive-ui-theme-icon/compose"
export type {ImmersiveUiThemeIconDatabase} from "@immersive-ui-theme-icon/database"
export type {ImmersiveUiThemeIconExecutionPoint} from "@immersive-ui-theme-icon/execution-point"
export type {ImmersiveUiThemeIconExpand} from "@immersive-ui-theme-icon/expand"
export type {ImmersiveUiThemeIconExpandAll} from "@immersive-ui-theme-icon/expand-all"
export type {ImmersiveUiThemeIconFolder} from "@immersive-ui-theme-icon/folder"
export type {ImmersiveUiThemeIconHome} from "@immersive-ui-theme-icon/home"
export type {ImmersiveUiThemeIconImage} from "@immersive-ui-theme-icon/image"
export type {ImmersiveUiThemeIconLanguage} from "@immersive-ui-theme-icon/language"
export type {ImmersiveUiThemeIconMinus} from "@immersive-ui-theme-icon/minus"
export type {ImmersiveUiThemeIconPicker} from "@immersive-ui-theme-icon/picker"
export type {ImmersiveUiThemeIconPin} from "@immersive-ui-theme-icon/pin"
export type {ImmersiveUiThemeIconPlus} from "@immersive-ui-theme-icon/plus"
export type {ImmersiveUiThemeIconResource} from "@immersive-ui-theme-icon/resource"
export type {ImmersiveUiThemeIconRun} from "@immersive-ui-theme-icon/run"
export type {ImmersiveUiThemeIconSearch} from "@immersive-ui-theme-icon/search"
export type {ImmersiveUiThemeIconSelectOpenedItem} from "@immersive-ui-theme-icon/select-opened-item"
export type {ImmersiveUiThemeIconSetting} from "@immersive-ui-theme-icon/setting"
export type {ImmersiveUiThemeIconVisibilityOn} from "@immersive-ui-theme-icon/visibility-on"
